EP-31: User registration and infrastructure (#9)
* Add User entity

* Change User entity and Repository

* Add RegisterUser usecase

* Add mockery and unit test for usecase

* Add dependecies

* Setup DB infrastructure: connection, creation, docker etc

* Add user repository implementation

* Adding rest client

* Feature complete

* Adding CI for unit tests

* Adjust code coverage

* Add functional test

* Clean up

* Some comments

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -24,5 +24,16 @@ jobs:
     - name: Build
       run: make build
 
-    # - name: Unit Test
-    #   run: make unit
+    - name: Unit Test
+      run: make unit
+
+    - name: Test Coverage
+      id: coverage-report
+      run: |
+        COVERAGE=$(make coverage-report | grep total: | awk '{print substr($3, 1, length($3)-1)}')
+        echo "Coverage: $COVERAGE%"
+        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
+         if (( $(echo "$COVERAGE < 70" |bc -l) )); then
+          echo "Code coverage below 70%. Failing..."
+          exit 1
+        fi
