better ci organization

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,6 +1,3 @@
-# This workflow will build a golang project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
-
 name: Easypark CI
 
 on:
@@ -10,13 +7,35 @@ on:
     branches: [ "main" ]
 
 jobs:
+  setup:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: '1.22.1'
+      - name: Cache Go modules
+        uses: actions/cache@v3
+        with:
+          path: ~/go/pkg/mod
+          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+          restore-keys: |
+            ${{ runner.os }}-go-
 
   build:
+    needs: setup
+    runs-on: ubuntu-latest
+    steps:
+      - name: Build
+        run: make build
+
+  test:
+    needs: build
     runs-on: ubuntu-latest
     services:
       database:
         image: postgres:latest
-        # Same as in docker-compose file
         env:
           POSTGRES_USER: devUser
           POSTGRES_PASSWORD: devPassword
@@ -28,47 +47,26 @@ jobs:
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
-
     steps:
-    - uses: actions/checkout@v3
+      - name: Wait for PostgreSQL
+        run: until pg_isready -h localhost -p 5432; do sleep 1; done
+      - name: Unit Test
+        run: make unit
+      - name: Test Coverage
+        id: coverage-report
+        run: |
+          COVERAGE=$(make coverage-report | grep total: | awk '{print substr($3, 1, length($3)-1)}')
+          echo "Coverage: $COVERAGE%"
+          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
+          if (( $(echo "$COVERAGE < 70" |bc -l) )); then
+            echo "Code coverage below 70%. Failing..."
+            exit 1
+          fi
+      - name: Functional Tests
+        run: |
+          make run &
+          APP_PID=$!
+          sleep 5
+          make functional
+          kill $APP_PID
 
-    - name: Set up Go
-      uses: actions/setup-go@v4
-      with:
-        go-version: '1.22.1'
-
-    - name: Cache Go modules
-      uses: actions/cache@v3
-      with:
-        path: ~/go/pkg/mod
-        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-        restore-keys: |
-          ${{ runner.os }}-go-
-
-    - name: Build
-      run: make build
-
-    - name: Unit Test
-      run: make unit
-
-    - name: Test Coverage
-      id: coverage-report
-      run: |
-        COVERAGE=$(make coverage-report | grep total: | awk '{print substr($3, 1, length($3)-1)}')
-        echo "Coverage: $COVERAGE%"
-        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
-         if (( $(echo "$COVERAGE < 70" |bc -l) )); then
-          echo "Code coverage below 70%. Failing..."
-          exit 1
-        fi
-    
-    - name: Wait for PostgreSQL
-      run: until pg_isready -h localhost -p 5432; do sleep 1; done
-
-    - name: Functional Tests
-      run: |
-        make run &
-        APP_PID=$!
-        sleep 5
-        make functional
-        kill $APP_PID
